### ISSUE TITLE
Zoom level resets on page change

### ISSUE THREAD

**Issue by k-kolev1985** [mush42/bookworm#20]
## Describe the Problem

If I change the zoom level of the text in an opened book and go to another page, zoom level resets. But executing the zoom-in/zoom-out commands continues to change from the last zoom level.

## To Reproduce

1. Open a book in Bookworm.
2. Use the zoom commands to increase or decrease the zoom level of the displayed book text.
3. Go to another page.
4. Observe how the zoom level will reset to default.
5. Use the zoom commands again to increase or decrease the zoom level on the new page.
6. Observe how the zoom level continues to change not from the default value to which it was reset during the page change, but from the level that it was on before the page change.

## Expected behavior

Bookworm should not reset the zoom level while changing the pages.

## Desktop (please complete the following information):

 - Operating system: Windows 10 Pro version 1903 (build 18362.356), 64-bit, in Bulgarian with all locale settings set to "Bulgarian".
 - Bookworm version: 0.1b3, x86 (32-bit).

**Comment by mush42** [comment]
Hi @k-kolev1985,

The issue is now fixed. With the following two additional enhancements:
* Changing the zoom level will not cause the zoom area to move to the top of the page
* Changing the page will not reset the zoom level, but it will scroll the zoom area to the top of the page

**Comment by k-kolev1985** [comment]
Is this fix supposed to be included in the build that you've provided to us for testing the support of OneCore voices? Because I can still reproduce it with it.

**Comment by mush42** [comment]
I don't thing so. The fix has been applied directly to the master branch, but the provided build has been built out of the develop branch.
I'll double check the commit history.
